name: deployment #Name of the workflow

on: [push]

jobs:
    test:         # Name of the job 1
        runs-on: ubuntu-latest # Selecting a GitHub Hosted Runner (Here selected an ubuntu machine)

        steps:                      # Automated Steps of the job
            - name: echo a string   # Name of the Step 1 (Optional)
              run: echo "Hello"     # command of the step 1

            - name: multiline commands  # Name of the Step 2
              run: |                    # Multiline commands of the step 2
                  node -v
                  npm -v

    deploy-secrets:
      runs-on: ubuntu-latest
      environment: github-pages
      steps:
            - name: define formspree key on env
              with: # Set the secret as an input
                REACT_APP_FORMSPREE_KEY: ${{ secrets.REACT_APP_FORMSPREE_KEY }}
              env:
                  REACT_APP_FORMSPREE_KEY: ${{ secrets.REACT_APP_FORMSPREE_KEY }}
              run: echo REACT_APP_FORMSPREE_KEY