name: deployment #Name of the workflow

#on: [push]
#branches: [ main ]

jobs:
    deploy-secrets:
      runs-on: ubuntu-latest
      environment: github-pages
      env:
        REACT_APP_FORMSPREE_KEY: ${{ secrets.REACT_APP_FORMSPREE_KEY }}
      steps:
        - uses: actions/checkout@v1
        - name: define formspree key on env
        - run:  REACT_APP_FORMSPREE_KEY = ${{ secrets.REACT_APP_FORMSPREE_KEY }}




#with: # Set the secret as an input
              #  REACT_APP_FORMSPREE_KEY: ${{ secrets.REACT_APP_FORMSPREE_KEY }}

#- name: Deploy to GitHub Pages
#  uses: JamesIves/github-pages-deploy-action@4.1.5


#- name: Setup Node.js environment
#  uses: actions/setup-node@v2.4.1